version: '3.4'
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://user:password@postgres:5432/myresume
      - SECRET_KEY_BASE=dev
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_S3_BUCKET=
      - AWS_S3_OBJECT_KEY=
    volumes:
      - $PWD:/home
    ports:
      - "5500:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.5.12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=myresume
