version: '3.4'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - rails_env=development
        - rack_env=development
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://user:password@postgres:5432/myresume
    volumes:
      - $PWD:/home
    ports:
      - "5500:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.5.12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=myresume

